from sage.forks.stable_baselines3.stable_baselines3.common.vec_env.obs_dict_wrapper import ObsDictWrapper
from sage.forks.stable_baselines3.stable_baselines3.her.goal_selection_strategy import GoalSelectionStrategy
from sage.forks.stable_baselines3.stable_baselines3.her.her import HER
from sage.forks.stable_baselines3.stable_baselines3.her.her_replay_buffer import HerReplayBuffer
